### ISSUE TITLE
file_sqlite as template function

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/apitest#34]
This function executes a select and returns the data much like the `file_csv` template function works.

## file_sqlite \<file> \<select>

Template Example:

```HTML+Django
{{{ file_sqlite "<file>" "SELECT "col_a", "col_B" FROM "<some table>" | marshal }}}
```

Output

```json
[
    {
        "col_a": "value row 0",
        "col_B": "value row 0"
    },
    {
        "col_a": "value row 1",
        "col_B": "value row 1"
    } ,
    "...."
]
```

**Comment by phempel** [comment]
@martinrode ready for testing: https://github.com/programmfabrik/apitest/pull/35

**Comment by phempel** [comment]
correct pull request (into develop): https://github.com/programmfabrik/apitest/pull/36

**Comment by phempel** [comment]
@martinrode fixes after review, ready for testing

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.
